### ISSUE TITLE
"ERROR: java.nio.file.Path.of(Ljava/net/URI;)Ljava/nio/file/Path;" during scan

### ISSUE THREAD

**Issue by gabrieldusaplannet** [insideapp-oss/sonar-flutter#17]
Hello,

We get the following error during "sonar-scanner" execution:
`11:44:20.460 ERROR: Error during SonarQube Scanner execution
java.lang.NoSuchMethodError: java.nio.file.Path.of(Ljava/net/URI;)Ljava/nio/file/Path;
	at fr.insideapp.sonarqube.flutter.tests.FlutterTestReportParser.parse(FlutterTestReportParser.java:40)
	at fr.insideapp.sonarqube.flutter.tests.FlutterTestSensor.execute(FlutterTestSensor.java:57)
	at org.sonar.scanner.sensor.AbstractSensorWrapper.analyse(AbstractSensorWrapper.java:48)
	at org.sonar.scanner.sensor.ModuleSensorsExecutor.execute(ModuleSensorsExecutor.java:85)
	at org.sonar.scanner.sensor.ModuleSensorsExecutor.lambda$execute$1(ModuleSensorsExecutor.java:59)
	at org.sonar.scanner.sensor.ModuleSensorsExecutor.withModuleStrategy(ModuleSensorsExecutor.java:77)
	at org.sonar.scanner.sensor.ModuleSensorsExecutor.execute(ModuleSensorsExecutor.java:59)
	at org.sonar.scanner.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:82)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:136)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:122)
	at org.sonar.scanner.scan.ProjectScanContainer.scan(ProjectScanContainer.java:386)
	at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:382)
	at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:351)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:136)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:122)
	at org.sonar.scanner.bootstrap.GlobalContainer.doAfterStart(GlobalContainer.java:141)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:136)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:122)
	at org.sonar.batch.bootstrapper.Batch.doExecute(Batch.java:72)
	at org.sonar.batch.bootstrapper.Batch.execute(Batch.java:66)
	at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:46)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
	at com.sun.proxy.$Proxy0.execute(Unknown Source)
	at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:185)
	at org.sonarsource.scanner.api.EmbeddedScanner.execute(EmbeddedScanner.java:137)
	at org.sonarsource.scanner.cli.Main.execute(Main.java:111)
	at org.sonarsource.scanner.cli.Main.execute(Main.java:75`

I attache the logs outputted by the "sonar-scanner -X > sonnar_scanner_logs.txt" command.

Is there anything we can do so that we get over this error?

Thanks!
[sonnar_scanner_logs.txt](https://github.com/insideapp-oss/sonar-flutter/files/4643074/sonnar_scanner_logs.txt)

**Comment by vasilich6107** [comment]
The easiest fix is to clone repo, replace `Path.of` with `Paths.get` as they are doing the same thing
https://stackoverflow.com/questions/58631724/paths-get-vs-path-of

and build the lib)

This could be easily achieved with Intelij Idea community edition or with command line)

Otherwise you can use my version 
[sonar-flutter-plugin-0.2.1.jar.zip](https://github.com/insideapp-oss/sonar-flutter/files/4681739/sonar-flutter-plugin-0.2.1.jar.zip)

**Comment by gabrieldusaplannet** [comment]
@vasilich6107 Thanks, your solution fixes our problem.

**Comment by vasilich6107** [comment]
@gabrieldusaplannet 
Good to hear!
I do not think that the issue worth closing...
Technically the  bug still exists without any suggestion of the possible fix.
My solution is some kind of temp one.
As soon as this issue is closed the author will not target to fix it for everyone

**Comment by mesudip** [comment]
I got this error when running the analysis in my jenkins. It was working correctly on my local machine.

 Apparantly `Path.of(java.net.URI)` is available only on JRE 1.11+

**Comment by matpag** [comment]
Readme should be updated to specify that to run or build from source we need JDK/OpenJDK 11

**Comment by zippy1978** [comment]
Thank you @ vasilich6107 !
I fixed it on develop branch.
