### ISSUE TITLE
Using a custom`analysis_options.yaml` generates an error durring issue reporting

### ISSUE THREAD

**Issue by 73VW** [insideapp-oss/sonar-flutter#179]
Hey there,

When using a custom `analysis_options.yaml` and not `sonar.dart.analyzer.options.override=true`, file restore crashes.

I have tried with various content but even with something as simple as [this](https://github.com/dart-lang/lints/blob/main/example/analysis_options.yaml) crashes.

Here's the output:

```
INFO: Detected Flutter project with version 1.0.0+1
INFO: Backup of original analysis_options.yaml file to analysis_options.yaml.sonar
INFO: Running 'flutter [analyze, --no-fatal-warnings, --no-fatal-infos]'
INFO: Command 'flutter analyze --no-fatal-warnings --no-fatal-infos' finished (exit 1)
INFO: Restored original analysis_options.yaml file
INFO: Recording 5042 issues
INFO: ------------------------------------------------------------------------
INFO: EXECUTION FAILURE
INFO: ------------------------------------------------------------------------
INFO: Total time: 47.256s
ERROR: Error during SonarScanner execution
INFO: Final Memory: 32M/114M
INFO: ------------------------------------------------------------------------
java.lang.IllegalArgumentException: 105 is not a valid line for pointer. File analysis_options.yaml has 72 line(s)
        at org.sonar.api.utils.Preconditions.checkArgument(Preconditions.java:43)
        at org.sonar.api.batch.fs.internal.DefaultInputFile.checkValid(DefaultInputFile.java:353)
        at org.sonar.api.batch.fs.internal.DefaultInputFile.newPointer(DefaultInputFile.java:289)
        at org.sonar.api.batch.fs.internal.DefaultInputFile.selectLine(DefaultInputFile.java:312)
        at fr.insideapp.sonarqube.dart.lang.issues.dartanalyzer.DartAnalyzerReportIssue.toNewIssueLocationFor(DartAnalyzerReportIssue.java:114)
        at fr.insideapp.sonarqube.dart.lang.issues.dartanalyzer.DartAnalyzerSensor.lambda$recordIssues$0(DartAnalyzerSensor.java:100)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
        at fr.insideapp.sonarqube.dart.lang.issues.dartanalyzer.DartAnalyzerSensor.recordIssues(DartAnalyzerSensor.java:89)
        at fr.insideapp.sonarqube.dart.lang.issues.dartanalyzer.DartAnalyzerSensor.execute(DartAnalyzerSensor.java:80)
        at org.sonar.scanner.sensor.AbstractSensorWrapper.analyse(AbstractSensorWrapper.java:64)
        at org.sonar.scanner.sensor.ModuleSensorsExecutor.execute(ModuleSensorsExecutor.java:88)
        at org.sonar.scanner.sensor.ModuleSensorsExecutor.lambda$execute$1(ModuleSensorsExecutor.java:61)
        at org.sonar.scanner.sensor.ModuleSensorsExecutor.withModuleStrategy(ModuleSensorsExecutor.java:79)
        at org.sonar.scanner.sensor.ModuleSensorsExecutor.execute(ModuleSensorsExecutor.java:61)
        at org.sonar.scanner.scan.SpringModuleScanContainer.doAfterStart(SpringModuleScanContainer.java:82)
        at org.sonar.core.platform.SpringComponentContainer.startComponents(SpringComponentContainer.java:188)
        at org.sonar.core.platform.SpringComponentContainer.execute(SpringComponentContainer.java:167)
        at org.sonar.scanner.scan.SpringProjectScanContainer.scan(SpringProjectScanContainer.java:403)
        at org.sonar.scanner.scan.SpringProjectScanContainer.scanRecursively(SpringProjectScanContainer.java:399)
        at org.sonar.scanner.scan.SpringProjectScanContainer.doAfterStart(SpringProjectScanContainer.java:368)
        at org.sonar.core.platform.SpringComponentContainer.startComponents(SpringComponentContainer.java:188)
        at org.sonar.core.platform.SpringComponentContainer.execute(SpringComponentContainer.java:167)
        at org.sonar.scanner.bootstrap.SpringGlobalContainer.doAfterStart(SpringGlobalContainer.java:137)
        at org.sonar.core.platform.SpringComponentContainer.startComponents(SpringComponentContainer.java:188)
        at org.sonar.core.platform.SpringComponentContainer.execute(SpringComponentContainer.java:167)
        at org.sonar.batch.bootstrapper.Batch.doExecute(Batch.java:72)
        at org.sonar.batch.bootstrapper.Batch.execute(Batch.java:66)
        at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:46)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
        at com.sun.proxy.$Proxy0.execute(Unknown Source)
        at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:189)
        at org.sonarsource.scanner.api.EmbeddedScanner.execute(EmbeddedScanner.java:138)
        at org.sonarsource.scanner.cli.Main.execute(Main.java:126)
        at org.sonarsource.scanner.cli.Main.execute(Main.java:81)
        at org.sonarsource.scanner.cli.Main.main(Main.java:62)
ERROR:
ERROR: Re-run SonarScanner using the -X switch to enable full debug logging.
```

Using `sonar.dart.analyzer.options.override=true` doesn't seem to fix the issue as it crashes with the same error.

**Comment by 73VW** [comment]
Ok so I am closing this because this isn't due to the plugin.

Launching the analysis manually on my local machine using `docker run --rm -e SONAR_HOST_URL=XXX -e SONAR_TOKEN=XXX -e SONAR_USER_HOME=/usr/src/.sonar -e GIT_DEPTH=0 -v ${PWD}:/usr/src/ vnvsa/sonar-scanner-cli-for-flutter:flutter-3.0.1 bash -c 'flutter pub get; flutter test; flutter test --machine --coverage > tests.output; sonar-scanner'` seems to work fine.

I am actually trying to debug the exact cause why it's not working in gitlab CI.

**Comment by 73VW** [comment]
I've made a few tests.

The error doesn't occur when restoring the file. I have tried to replace the lines

``` java
            if (optionsCreated) {
                restoreAnalysisOptionsFile(sensorContext);
            }
```

with a logger line and I still get the same error.

The error happens during issue reporting. I am still debugging and will keep you updated as soon as I know more.

**Comment by 73VW** [comment]
I've updated the method `DartAnalyzerSensor.execute this way to obtain more output:

``` java
    @Override
    @ParametersAreNonnullByDefault
    public void execute(SensorContext sensorContext) {
        try {
            final PubSpec pubSpec = PubSpecParser.parse(sensorContext);
            final AnalyzerOutput output = AnalyzerExecutable.create(sensorContext, pubSpec).analyze();

            DartAnalyzerReportParser parser = new FlutterAnalyzerReportParser();

            LOGGER.info("Mode");
            LOGGER.info(output.getMode().toString());
            if (!output.getAnalyzerMode().equals(AnalyzerExecutable.Mode.FLUTTER)) {
                parser = output.getMode().equals(AnalyzerOutput.Mode.MACHINE)
                        ? new DartAnalyzerMachineReportParser() : new DartAnalyzerLegacyReportParser();
            }

            LOGGER.info("Output");
            LOGGER.info(output.getContent());

            final List<DartAnalyzerReportIssue> issues = parser.parse(output.getContent());

            LOGGER.info("Recording {} issues", issues.size());

            recordIssues(sensorContext, issues);
        } catch (IOException e) {
            LOGGER.error("Analysis failed", e);
        }


    }
```

Here's the truncated output:

``` bash
...
INFO: Mode
INFO: LEGACY
INFO: Output
INFO: Analyzing src...                                                

warning • 'collection_methods_unrelated_type' is not a recognized lint rule • analysis_options.yaml:14:7 • undefined_lint_warning
warning • 'deprecated_member_use_from_same_package' is not a recognized lint rule • analysis_options.yaml:17:7 • undefined_lint_warning
warning • 'discarded_futures' is not a recognized lint rule • analysis_options.yaml:19:7 • undefined_lint_warning
warning • 'implicit_reopen' is not a recognized lint rule • analysis_options.yaml:22:7 • undefined_lint_warning
warning • 'invalid_case_patterns' is not a recognized lint rule • analysis_options.yaml:23:7 • undefined_lint_warning
   info • 'avoid_as' is a deprecated lint rule and should not be used • analysis_options.yaml:46:7 • deprecated_lint_hint
warning • The rule 'avoid_types_on_closure_parameters' is incompatible with the rule 'always_specify_types' • analysis_options.yaml:72:7 • incompatible_lint_warning
warning • 'combinators_ordering' is not a recognized lint rule • analysis_options.yaml:81:7 • undefined_lint_warning
warning • 'dangling_library_doc_comments' is not a recognized lint rule • analysis_options.yaml:85:7 • undefined_lint_warning
warning • 'enable_null_safety' is not a recognized lint rule • analysis_options.yaml:91:7 • undefined_lint_warning
warning • 'implicit_call_tearoffs' is not a recognized lint rule • analysis_options.yaml:97:7 • undefined_lint_warning
warning • 'library_annotations' is not a recognized lint rule • analysis_options.yaml:100:7 • undefined_lint_warning
warning • 'matching_super_parameters' is not a recognized lint rule • analysis_options.yaml:105:7 • undefined_lint_warning
warning • 'no_literal_bool_comparisons' is not a recognized lint rule • analysis_options.yaml:110:7 • undefined_lint_warning
warning • The rule 'omit_local_variable_types' is incompatible with the rule 'always_specify_types' • analysis_options.yaml:116:7 • incompatible_lint_warning
   info • 'prefer_bool_in_asserts' is a deprecated lint rule and should not be used • analysis_options.yaml:126:7 • deprecated_lint_hint
warning • The rule 'prefer_final_parameters' is incompatible with the rule 'avoid_final_parameters' • analysis_options.yaml:141:7 • incompatible_lint_warning
warning • The rule 'prefer_single_quotes' is incompatible with the rule 'prefer_double_quotes' • analysis_options.yaml:159:7 • incompatible_lint_warning
   info • 'super_goes_last' is a deprecated lint rule and should not be used • analysis_options.yaml:172:7 • deprecated_lint_hint
warning • 'type_literal_in_constant_pattern' is not a recognized lint rule • analysis_options.yaml:176:7 • undefined_lint_warning
warning • 'unnecessary_breaks' is not a recognized lint rule • analysis_options.yaml:180:7 • undefined_lint_warning
warning • The rule 'unnecessary_final' is incompatible with the rule 'prefer_final_locals' • analysis_options.yaml:183:7 • incompatible_lint_warning
warning • 'unnecessary_library_directive' is not a recognized lint rule • analysis_options.yaml:187:7 • undefined_lint_warning
warning • 'unnecessary_null_aware_operator_on_extension_on_nullable' is not a recognized lint rule • analysis_options.yaml:190:7 • undefined_lint_warning
warning • 'unnecessary_to_list_in_spreads' is not a recognized lint rule • analysis_options.yaml:200:7 • undefined_lint_warning
warning • 'unreachable_from_main' is not a recognized lint rule • analysis_options.yaml:201:7 • undefined_lint_warning
warning • 'use_string_in_part_of_directives' is not a recognized lint rule • analysis_options.yaml:215:7 • undefined_lint_warning
warning • 'abi_specific_integer_invalid' is not a recognized lint rule • analysis_options.yaml:222:7 • undefined_lint_warning
warning • 'abstract_field_initializer' is not a recognized lint rule • analysis_options.yaml:223:7 • undefined_lint_warning
warning • 'argument_type_not_assignable_to_error_handler' is not a recognized lint rule • analysis_options.yaml:224:7 • undefined_lint_warning
warning • 'body_might_complete_normally' is not a recognized lint rule • analysis_options.yaml:225:7 • undefined_lint_warning
warning • 'conflicting_constructor_and_static_member' is not a recognized lint rule • analysis_options.yaml:226:7 • undefined_lint_warning
warning • 'const_map_key_not_primitive_equality' is not a recognized lint rule • analysis_options.yaml:227:7 • undefined_lint_warning
warning • 'dead_null_aware_expression' is not a recognized lint rule • analysis_options.yaml:228:7 • undefined_lint_warning
warning • 'deprecated_new_in_comment_reference' is not a recognized lint rule • analysis_options.yaml:229:7 • undefined_lint_warning
warning • 'duplicate_constructor' is not a recognized lint rule • analysis_options.yaml:230:7 • undefined_lint_warning
warning • 'duplicate_field_name' is not a recognized lint rule • analysis_options.yaml:231:7 • undefined_lint_warning
warning • 'duplicate_ignore' is not a recognized lint rule • analysis_options.yaml:232:7 • undefined_lint_warning
warning • 'duplicate_pattern_field' is not a recognized lint rule • analysis_options.yaml:233:7 • undefined_lint_warning
warning • 'external_with_initializer' is not a recognized lint rule • analysis_options.yaml:234:7 • undefined_lint_warning
warning • 'field_initializer_redirecting_constructor' is not a recognized lint rule • analysis_options.yaml:235:7 • undefined_lint_warning
warning • 'illegal_concrete_enum_member' is not a recognized lint rule • analysis_options.yaml:236:7 • undefined_lint_warning
warning • 'illegal_enum_values' is not a recognized lint rule • analysis_options.yaml:237:7 • undefined_lint_warning
warning • 'implicit_super_initializer_missing_arguments' is not a recognized lint rule • analysis_options.yaml:238:7 • undefined_lint_warning
warning • 'inconsistent_pattern_variable_logical_or' is not a recognized lint rule • analysis_options.yaml:239:7 • undefined_lint_warning
warning • 'invalid_annotation' is not a recognized lint rule • analysis_options.yaml:240:7 • undefined_lint_warning
warning • 'invalid_extension_argument_count' is not a recognized lint rule • analysis_options.yaml:241:7 • undefined_lint_warning
warning • 'invalid_field_name' is not a recognized lint rule • analysis_options.yaml:242:7 • undefined_lint_warning
warning • 'invalid_literal_annotation' is not a recognized lint rule • analysis_options.yaml:243:7 • undefined_lint_warning
warning • 'invalid_non_virtual_annotation' is not a recognized lint rule • analysis_options.yaml:244:7 • undefined_lint_warning
warning • 'invalid_null_aware_operator' is not a recognized lint rule • analysis_options.yaml:245:7 • undefined_lint_warning
warning • 'invalid_pattern_variable_in_shared_case_scope' is not a recognized lint rule • analysis_options.yaml:246:7 • undefined_lint_warning
warning • 'invalid_return_type_for_catch_error' is not a recognized lint rule • analysis_options.yaml:247:7 • undefined_lint_warning
warning • 'invalid_super_formal_parameter_location' is not a recognized lint rule • analysis_options.yaml:248:7 • undefined_lint_warning
warning • 'invalid_type_argument_in_const_literal' is not a recognized lint rule • analysis_options.yaml:249:7 • undefined_lint_warning
warning • 'invocation_of_non_function_expression' is not a recognized lint rule • analysis_options.yaml:250:7 • undefined_lint_warning
warning • 'missing_default_value_for_parameter' is not a recognized lint rule • analysis_options.yaml:251:7 • undefined_lint_warning
warning • 'non_constant_map_element' is not a recognized lint rule • analysis_options.yaml:252:7 • undefined_lint_warning
warning • 'not_assigned_potentially_non_nullable_local_variable' is not a recognized lint rule • analysis_options.yaml:253:7 • undefined_lint_warning
warning • 'not_initialized_non_nullable_instance_field' is not a recognized lint rule • analysis_options.yaml:254:7 • undefined_lint_warning
warning • 'not_initialized_non_nullable_variable' is not a recognized lint rule • analysis_options.yaml:255:7 • undefined_lint_warning
warning • 'recursive_constructor_redirect' is not a recognized lint rule • analysis_options.yaml:256:7 • undefined_lint_warning
warning • 'redirect_to_invalid_function_type' is not a recognized lint rule • analysis_options.yaml:257:7 • undefined_lint_warning
warning • 'return_in_generator' is not a recognized lint rule • analysis_options.yaml:258:7 • undefined_lint_warning
warning • 'subtype_of_disallowed_type' is not a recognized lint rule • analysis_options.yaml:259:7 • undefined_lint_warning
warning • 'super_formal_parameter_without_associated_positional' is not a recognized lint rule • analysis_options.yaml:260:7 • undefined_lint_warning
warning • 'type_check_with_null' is not a recognized lint rule • analysis_options.yaml:261:7 • undefined_lint_warning
warning • 'type_parameter_supertype_of_its_bound' is not a recognized lint rule • analysis_options.yaml:262:7 • undefined_lint_warning
warning • 'undefined_constructor_in_initializer' is not a recognized lint rule • analysis_options.yaml:263:7 • undefined_lint_warning
warning • 'undefined_enum_constructor' is not a recognized lint rule • analysis_options.yaml:264:7 • undefined_lint_warning
warning • 'undefined_extension_getter' is not a recognized lint rule • analysis_options.yaml:265:7 • undefined_lint_warning
warning • 'undefined_extension_method' is not a recognized lint rule • analysis_options.yaml:266:7 • undefined_lint_warning
warning • 'undefined_extension_setter' is not a recognized lint rule • analysis_options.yaml:267:7 • undefined_lint_warning
warning • 'undefined_super_member' is not a recognized lint rule • analysis_options.yaml:268:7 • undefined_lint_warning
warning • The rule 'unnecessary_final' is incompatible with the rule 'prefer_final_locals' • analysis_options.yaml:269:7 • incompatible_lint_warning
warning • 'unnecessary_null_comparison' is not a recognized lint rule • analysis_options.yaml:270:7 • undefined_lint_warning
warning • 'wrong_number_of_parameters_for_setter' is not a recognized lint rule • analysis_options.yaml:271:7 • undefined_lint_warning
warning • 'wrong_number_of_type_arguments' is not a recognized lint rule • analysis_options.yaml:272:7 • undefined_lint_warning
warning • 'yield_in_non_generator' is not a recognized lint rule • analysis_options.yaml:273:7 • undefined_lint_warning
...
```

There are errors in the `analysis_options.yaml` file that your plugin provides.

I am going to investigate why the parser looks in the wrong file when trying to read the content of `analysis_options.yaml`

If I skip file restoration, the file `analysis_options.yaml` keeps the content you put in:

``` bash
$ cat analysis_options.yaml | wc -l
273
```
Error is still ` 81 is not a valid line for pointer. File analysis_options.yaml has 73 line(s)` in the logs.

**Comment by 73VW** [comment]
I suspect that `sensorContext.fileSystem()` is instantiated at the very beginning and keeps a "cache" of the files. That would explain why it crashes when it detects an error in your `analysis_options.yaml` and mine is shorter.

**Comment by aharris** [comment]
Any update here? I am having the same issue.

**Comment by aharris** [comment]
I excluded `analysis_options.yaml` for the time being:

```
sonar.exclusions=analysis_options.yaml
```

**Comment by friedScotch** [comment]
> Any update here? I am having the same issue.

As I mentioned in https://github.com/insideapp-oss/sonar-flutter/issues/180 , use `sonar.dart.analyzer.options.override=false` if you want to use your custom analysis.yml file

**Comment by 73VW** [comment]
@friedScotch That has nothing to do with the bug.

The bug occurs in the following condition:

- Your repository contains a file `analysis_options.yaml` shorter than the one from here.
- You don't use the option to override the use of the one from here.

**Comment by zippy1978** [comment]
Hi @73VW,

I suspect you are trying to analyse your own `analysis_options.yaml`: the analysis is done...
And to keep it short: you should exclude it from your sources.

Make sure to not put it in `sonar.sources`, or explicitly exclude it with `sonar.exclusions`
