### ISSUE TITLE
Flutter analysis not working in Azure Devops plugin SonarQubeAnalyze@5

### ISSUE THREAD

**Issue by ex2-atewatia** [insideapp-oss/sonar-flutter#186]
When I try to run flutter analysis using sonar-flutter plugin in Azure Devops pipeline task `SonarQubeAnalysis@5`, I get the error `##[error]ERROR: org.buildobjects.process.StartupException: Could not startup process 'flutter analyze'.`
Apparently, AzureDevops task isn't able to find flutter. However, I installed flutter explicitly in previous `Bash@3` task.

**Comment by zippy1978** [comment]
Hi @ex2-atewatia,

Eventhough flutter is installed the `flutter` command may not be on the path. Use the full path to your flutter executable to call the command.

Or you can add the command to the path in you bash install script with something like ``export PATH=`pwd`/flutter/bin:$PATH``.

**Comment by roofiq** [comment]
Hey @zippy1978 
I have similar issue so will write here. I want to run sqonarqube againts flutter on azure devops hosted macos agent.

I'm getting below error:
```
Caused by: java.io.IOException: Cannot run program "flutter" (in directory "/Users/runner/work/1/s/src/app"): error=2, No such file or directory
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
	at java.base/java.lang.Runtime.exec(Runtime.java:592)
	at org.buildobjects.process.Proc.<init>(Proc.java:77)
	... 33 more
Caused by: java.io.IOException: error=2, No such file or directory
	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:340)
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:271)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)
	... 36 more
##[debug]Exit code 1 received from tool '/Users/runner/work/_tasks/SonarQubeAnalyze_6d01813a-9589-4b15-8491-8164aeb38055/5.15.0/sonar-scanner/bin/sonar-scanner'
##[debug]STDIO streams have closed for tool '/Users/runner/work/_tasks/SonarQubeAnalyze_6d01813a-9589-4b15-8491-8164aeb38055/5.15.0/sonar-scanner/bin/sonar-scanner'
##[debug]task result: Failed
##[error]The process '/Users/runner/work/_tasks/SonarQubeAnalyze_6d01813a-9589-4b15-8491-8164aeb38055/5.15.0/sonar-scanner/bin/sonar-scanner' failed with exit code 1
```

I have added flutter to PATH. 
My `sonar-project.properties`:
```
sonar.projectName=Mobile
sonar.projectKey=xxx
sonar.projectBaseDir=src/app # base dir of my flutter app
```

Sonarqube tasks:
```
steps:
# Prepare Analysis Configuration task
- task: SonarQubePrepare@5
  inputs:
    SonarQube: 'sonarqube'
    scannerMode: 'CLI'
    configMode: 'file'
    cliProjectKey: xxx
    configFile: 'sonar-project.properties'
# - script: | # works well so flutter is in PATH
#     flutter analyze --no-fatal-warnings --no-fatal-infos
#   workingDirectory: '$(Build.SourcesDirectory)/src/app'
# Run Code Analysis task
- task: SonarQubeAnalyze@5
  inputs:
    jdkversion: 'JAVA_HOME_11_X64'
# Publish Quality Gate Result task
- task: SonarQubePublish@5
  inputs:
    pollingTimeoutSec: '300'
```

Any ideas? I'm running sonarqube on 9.9 LTS.

Thanks!
Rafal
