### ISSUE TITLE
Could not startup process 'flutter analyze --no-fatal-warnings --no-fatal-infos'

### ISSUE THREAD

**Issue by msaad2110** [insideapp-oss/sonar-flutter#190]
I have installed Sonar Scanner on my GitLab server, along with Flutter and Dart, but I keep getting this error log while trying to run Job using Sonar Scanner, 

`ERROR: Error during SonarScanner execution
org.buildobjects.process.StartupException: Could not startup process 'flutter analyze --no-fatal-warnings --no-fatal-infos'.
	at org.buildobjects.process.Proc.<init>(Proc.java:91)
	at org.buildobjects.process.ProcBuilder.run(ProcBuilder.java:205)
	at fr.insideapp.sonarqube.dart.lang.issues.dartanalyzer.executable.AnalyzerExecutable.analyze(AnalyzerExecutable.java:88)
	at fr.insideapp.sonarqube.dart.lang.issues.dartanalyzer.DartAnalyzerSensor.execute(DartAnalyzerSensor.java:67)
	at org.sonar.scanner.sensor.AbstractSensorWrapper.analyse(AbstractSensorWrapper.java:64)
	at org.sonar.scanner.sensor.ModuleSensorsExecutor.execute(ModuleSensorsExecutor.java:88)
	at org.sonar.scanner.sensor.ModuleSensorsExecutor.lambda$execute$1(ModuleSensorsExecutor.java:61)
	at org.sonar.scanner.sensor.ModuleSensorsExecutor.withModuleStrategy(ModuleSensorsExecutor.java:79)
	at org.sonar.scanner.sensor.ModuleSensorsExecutor.execute(ModuleSensorsExecutor.java:61)
	at org.sonar.scanner.scan.SpringModuleScanContainer.doAfterStart(SpringModuleScanContainer.java:82)
	at org.sonar.core.platform.SpringComponentContainer.startComponents(SpringComponentContainer.java:188)
	at org.sonar.core.platform.SpringComponentContainer.execute(SpringComponentContainer.java:167)` 
	
The flutter analyze seems to be working fine in the pipeline, If I issue the command directly but with the sonar scanner it keeps getting failed.

**Comment by msaad2110** [comment]
Fixed this was related to Sonar-Scanner permissions

**Comment by roofiq** [comment]
Hey @msaad2110, I'm facing the same issue. How to change permission for sonar-scanner?

**Comment by jagadeesh7860** [comment]
Hey @msaad2110, Can you please explain how to solve this issue?

**Comment by jasonred8** [comment]
@jagadeesh7860 you can have a try https://github.com/insideapp-oss/sonar-flutter/issues/177#issuecomment-1569087476
It has solved my issue.
