### ISSUE TITLE
Sonar-Flutter Plugin not working in SonarQube 9.9.x or 10.2.x

### ISSUE THREAD

**Issue by eblackssc** [insideapp-oss/sonar-flutter#198]
When the plugin is in the sonarqube extensions folder, the web server will start and then fail and the server will stop. Removing the plugin from the extensions folder, sonarqube runs just as it should. Below is the web log which shows Error. This is running on a CentOS 7 VM.

```
2023.10.26 11:34:51 INFO  web[][o.s.p.ProcessEntryPoint] Starting Web Server
2023.10.26 11:34:53 INFO  web[][o.s.s.p.LogServerVersion] SonarQube Server / 9.9.2.77730 / dd63ff5d0db91f039afd5d40319122666c9961ef
2023.10.26 11:34:53 INFO  web[][o.s.s.p.d.EmbeddedDatabase] Starting embedded database on port 9092 with url jdbc:h2:tcp://127.0.0.1:9092/sonar;NON_KEYWORDS=VALUE
2023.10.26 11:34:53 INFO  web[][o.s.s.p.d.EmbeddedDatabase] Embedded database started. Data stored in: /home/sonarqube/sonarqube-9.9.2.77730/data
2023.10.26 11:34:53 INFO  web[][o.sonar.db.Database] Create JDBC data source for jdbc:h2:tcp://127.0.0.1:9092/sonar;NON_KEYWORDS=VALUE
2023.10.26 11:34:53 INFO  web[][c.z.h.HikariDataSource] HikariPool-1 - Starting...
2023.10.26 11:34:54 INFO  web[][c.z.h.p.HikariPool] HikariPool-1 - Added connection conn2: url=jdbc:h2:tcp://127.0.0.1:9092/sonar user=
2023.10.26 11:34:54 INFO  web[][c.z.h.HikariDataSource] HikariPool-1 - Start completed.
2023.10.26 11:34:54 WARN  web[][o.s.db.dialect.H2] H2 database should be used for evaluation purpose only.
2023.10.26 11:34:55 INFO  web[][o.s.s.p.ServerFileSystemImpl] SonarQube home: /home/sonarqube/sonarqube-9.9.2.77730
2023.10.26 11:34:55 INFO  web[][o.s.s.u.SystemPasscodeImpl] System authentication by passcode is disabled
2023.10.26 11:34:55 INFO  web[][o.s.c.e.CoreExtensionsLoader] Loaded core extensions: developer-edition, developer-scanner, developer-server, license, monitoring
2023.10.26 11:34:55 INFO  web[][o.s.s.p.ServerPluginManager] Deploy ABAP Code Quality and Security / 3.11.0.4030 / efe73c1da897a69d2545e79710bec0909326dcdb
2023.10.26 11:34:55 INFO  web[][o.s.s.p.ServerPluginManager] Deploy C# Code Quality and Security / 8.51.0.59060 / e14c642f118958f22fd08841dc42f9aae480366a
2023.10.26 11:34:55 INFO  web[][o.s.s.p.ServerPluginManager] Deploy CFamily Code Quality and Security / 6.41.1.62265 / 9a86fb481d3f05ac5d3fc7d21aa20f88534a8cfe
2023.10.26 11:34:55 INFO  web[][o.s.s.p.ServerPluginManager] Deploy Configuration detection fot Code Quality and Security / 1.2.0.267 / 4f37ba9ffb37a96d5883e52ad392ed32c5c6eaab
2023.10.26 11:34:55 INFO  web[][o.s.s.p.ServerPluginManager] Deploy Dataflow Bug Detection / 1.10.0.3046 / 0
2023.10.26 11:34:55 INFO  web[][o.s.s.p.ServerPluginManager] Deploy Dataflow Bug Detection Rules for Java / 1.10.0.3046 / 0
2023.10.26 11:34:55 INFO  web[][o.s.s.p.ServerPluginManager] Deploy Dataflow Bug Detection Rules for Python / 1.10.0.3046 / 0
2023.10.26 11:34:55 INFO  web[][o.s.s.p.ServerPluginManager] Deploy Flex Code Quality and Security / 2.8.0.3166 / 01f66bdddc678966c81a9064ed139156a6a89c97
2023.10.26 11:34:55 INFO  web[][o.s.s.p.ServerPluginManager] Deploy Flutter / 0.2.1 / e7babbc2f0d2b01a5bda572234091c0302fcb18a
2023.10.26 11:34:55 INFO  web[][o.s.s.p.ServerPluginManager] Deploy Go Code Quality and Security / 1.11.0.3905 / e1f28bc000e04ca01881e84218d01d464a17a36f
2023.10.26 11:34:55 INFO  web[][o.s.s.p.ServerPluginManager] Deploy HTML Code Quality and Security / 3.7.1.3306 / d720acc6860c6d8b69ec4d17570a398a1e216da1
2023.10.26 11:34:55 INFO  web[][o.s.s.p.ServerPluginManager] Deploy IaC Code Quality and Security / 1.11.0.2847 / 6892bd3a7320b3c110717acfdb18c4c7451069fd
2023.10.26 11:34:55 INFO  web[][o.s.s.p.ServerPluginManager] Deploy JaCoCo / 1.3.0.1538 / 74a7798c7cea687c72ed9df40c93eb7ea2a58c49
2023.10.26 11:34:55 INFO  web[][o.s.s.p.ServerPluginManager] Deploy Java Code Quality and Security / 7.16.0.30901 / 4b1436558dfd5fc00c8d9aae8bb0364ba122c73e
2023.10.26 11:34:55 INFO  web[][o.s.s.p.ServerPluginManager] Deploy JavaScript/TypeScript/CSS Code Quality and Security / 9.13.0.20537 / 68ff7657415044b86033814795ed95fc1f1558f1
2023.10.26 11:34:55 INFO  web[][o.s.s.p.ServerPluginManager] Deploy Kotlin Code Quality and Security / 2.12.0.1956 / a6df1ae252bd62d63f8673c28f87ad14258a7904
2023.10.26 11:34:55 INFO  web[][o.s.s.p.ServerPluginManager] Deploy PHP Code Quality and Security / 3.27.1.9352 / 3ddc5a03e1a7e3729d41e7c1a30a37d5715958c7
2023.10.26 11:34:55 INFO  web[][o.s.s.p.ServerPluginManager] Deploy PL/SQL Code Quality and Security / 3.8.0.4948 / ab46f4c11644e5c9b17f0a5a1612d4b7362e04f3
2023.10.26 11:34:55 INFO  web[][o.s.s.p.ServerPluginManager] Deploy Python Code Quality and Security / 3.24.1.11916 / cc8f4fa745eb33d31c3869bdfdfd45514e67c1fe
2023.10.26 11:34:55 INFO  web[][o.s.s.p.ServerPluginManager] Deploy Ruby Code Quality and Security / 1.11.0.3905 / e1f28bc000e04ca01881e84218d01d464a17a36f
2023.10.26 11:34:55 INFO  web[][o.s.s.p.ServerPluginManager] Deploy Scala Code Quality and Security / 1.11.0.3905 / e1f28bc000e04ca01881e84218d01d464a17a36f
2023.10.26 11:34:55 INFO  web[][o.s.s.p.ServerPluginManager] Deploy Swift Code Quality and Security / 4.8.0.5759 / 3d5b95aaf19a398736a7f5eec314c3c05f7193d2
2023.10.26 11:34:55 INFO  web[][o.s.s.p.ServerPluginManager] Deploy T-SQL Code Quality and Security / 1.7.0.5449 / 110c82f888b1f40e1c2a0d3165fcffd413af36a5
2023.10.26 11:34:55 INFO  web[][o.s.s.p.ServerPluginManager] Deploy Text Code Quality and Security / 2.0.2.1090 / 7eb026363b98f5f98b43c603772b5177869c2c6a
2023.10.26 11:34:55 INFO  web[][o.s.s.p.ServerPluginManager] Deploy VB.NET Code Quality and Security / 8.51.0.59060 / e14c642f118958f22fd08841dc42f9aae480366a
2023.10.26 11:34:55 INFO  web[][o.s.s.p.ServerPluginManager] Deploy Vulnerability Analysis / 9.9.2.22117 / 63ec18952dc2268064c095158aa5136ee596afe0
2023.10.26 11:34:55 INFO  web[][o.s.s.p.ServerPluginManager] Deploy Vulnerability Rules for C# / 9.9.2.22117 / 63ec18952dc2268064c095158aa5136ee596afe0
2023.10.26 11:34:55 INFO  web[][o.s.s.p.ServerPluginManager] Deploy Vulnerability Rules for JS / 9.9.2.22117 / 63ec18952dc2268064c095158aa5136ee596afe0
2023.10.26 11:34:55 INFO  web[][o.s.s.p.ServerPluginManager] Deploy Vulnerability Rules for Java / 9.9.2.22117 / 63ec18952dc2268064c095158aa5136ee596afe0
2023.10.26 11:34:55 INFO  web[][o.s.s.p.ServerPluginManager] Deploy Vulnerability Rules for PHP / 9.9.2.22117 / 63ec18952dc2268064c095158aa5136ee596afe0
2023.10.26 11:34:55 INFO  web[][o.s.s.p.ServerPluginManager] Deploy Vulnerability Rules for Python / 9.9.2.22117 / 63ec18952dc2268064c095158aa5136ee596afe0
2023.10.26 11:34:55 INFO  web[][o.s.s.p.ServerPluginManager] Deploy XML Code Quality and Security / 2.7.0.3820 / 656bccc1910d50c8984536bd2dfd917066b858e6
2023.10.26 11:35:04 INFO  web[][o.s.s.e.EsClientProvider] Connected to local Elasticsearch: [http://localhost:9001]
2023.10.26 11:35:04 WARN  web[][o.s.a.s.w.WebService$Action] Description is not set on action api/monitoring/metrics
2023.10.26 11:35:04 WARN  web[][o.s.a.s.w.WebService$Action] Since is not set on action api/monitoring/metrics
2023.10.26 11:35:04 WARN  web[][o.s.a.s.w.WebService$Action] The response example is not set on action api/monitoring/metrics
2023.10.26 11:35:04 WARN  web[][o.s.a.s.w.WebService$Action] The response example is not set on action api/system/liveness
2023.10.26 11:35:04 INFO  web[][o.s.s.p.w.MasterServletFilter] Initializing servlet filter org.sonar.server.platform.web.WebServiceFilter@4264beb8 [pattern=UrlPattern{inclusions=[/api/system/migrate_db.*, ...], exclusions=[/api/components/update_key, ...]}]
2023.10.26 11:35:04 INFO  web[][o.s.s.p.DetectPluginChange] Detect plugin changes
2023.10.26 11:35:05 INFO  web[][o.s.s.a.EmbeddedTomcat] HTTP connector enabled on port 9000
2023.10.26 11:35:06 INFO  web[][o.s.s.s.LogServerId] Server ID: 147B411E-AYtdtEzuNGs7TVyBAg-q
2023.10.26 11:35:06 WARN  web[][o.s.s.a.LogOAuthWarning] For security reasons, OAuth authentication should use HTTPS. You should set the property 'Administration > Configuration > Server base URL' to a HTTPS URL.
2023.10.26 11:35:06 INFO  web[][o.s.s.p.UpdateCenterClient] Update center: https://update.sonarsource.org/update-center.properties
2023.10.26 11:35:07 WARN  web[][o.s.a.s.w.WebService$Action] The response example is not set on action saml/validation_init
2023.10.26 11:35:07 WARN  web[][o.s.a.s.w.WebService$Action] The response example is not set on action api/system/liveness
2023.10.26 11:35:07 WARN  web[][o.s.a.s.w.WebService$Action] The response example is not set on action api/plugins/download
2023.10.26 11:35:07 WARN  web[][o.s.a.s.w.WebService$Action] The response example is not set on action api/analysis_cache/get
2023.10.26 11:35:07 WARN  web[][o.s.a.s.w.WebService$Action] The response example is not set on action api/alm_integrations/check_pat
2023.10.26 11:35:07 WARN  web[][o.s.a.s.w.WebService$Action] The response example is not set on action api/push/sonarlint_events
2023.10.26 11:35:07 WARN  web[][o.s.a.s.w.WebService$Action] The response example is not set on action api/support/info
2023.10.26 11:35:07 INFO  web[][o.s.s.a.p.ExpiredSessionsCleaner] Purge of expired session tokens has removed 0 elements
2023.10.26 11:35:07 INFO  web[][o.s.s.a.p.ExpiredSessionsCleaner] Purge of expired SAML message ids has removed 0 elements
2023.10.26 11:35:07 INFO  web[][o.s.s.n.NotificationDaemon] Notification service started (delay 60 sec.)
2023.10.26 11:35:07 INFO  web[][o.s.s.t.TelemetryDaemon] Sharing of SonarQube statistics is enabled.
2023.10.26 11:35:07 INFO  web[][o.s.s.s.GeneratePluginIndex] Generate scanner plugin index
2023.10.26 11:35:07 INFO  web[][o.s.s.s.RegisterMetrics] Register metrics
2023.10.26 11:35:07 INFO  web[][o.s.s.r.RegisterRules] Register rules
2023.10.26 11:35:09 WARN  web[][o.s.c.a.AnnotationConfigApplicationContext] Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'jdk.internal.loader.ClassLoaders$AppClassLoader@5ffd2b27-org.sonar.server.rule.RegisterRules': Initialization of bean failed; nested exception is java.lang.NoSuchMethodError: 'org.sonar.api.server.rule.RulesDefinition$NewRule org.sonar.api.server.rule.RulesDefinition$NewRule.setDebtSubCharacteristic(java.lang.String)'
2023.10.26 11:35:09 ERROR web[][o.s.s.p.Platform] Background initialization failed. Stopping SonarQube
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'jdk.internal.loader.ClassLoaders$AppClassLoader@5ffd2b27-org.sonar.server.rule.RegisterRules': Initialization of bean failed; nested exception is java.lang.NoSuchMethodError: 'org.sonar.api.server.rule.RulesDefinition$NewRule org.sonar.api.server.rule.RulesDefinition$NewRule.setDebtSubCharacteristic(java.lang.String)'
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:628)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:955)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:920)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583)
	at org.sonar.core.platform.SpringComponentContainer.startComponents(SpringComponentContainer.java:187)
	at org.sonar.server.platform.platformlevel.PlatformLevel.start(PlatformLevel.java:80)
	at org.sonar.server.platform.platformlevel.PlatformLevelStartup.access$001(PlatformLevelStartup.java:55)
	at org.sonar.server.platform.platformlevel.PlatformLevelStartup$1.doPrivileged(PlatformLevelStartup.java:127)
	at org.sonar.server.user.DoPrivileged.execute(DoPrivileged.java:45)
	at org.sonar.server.platform.platformlevel.PlatformLevelStartup.start(PlatformLevelStartup.java:124)
	at org.sonar.server.platform.PlatformImpl.executeStartupTasks(PlatformImpl.java:183)
	at org.sonar.server.platform.PlatformImpl$AutoStarterRunnable.runIfNotAborted(PlatformImpl.java:344)
	at org.sonar.server.platform.PlatformImpl$1.doRun(PlatformImpl.java:107)
	at org.sonar.server.platform.PlatformImpl$AutoStarterRunnable.run(PlatformImpl.java:328)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.NoSuchMethodError: 'org.sonar.api.server.rule.RulesDefinition$NewRule org.sonar.api.server.rule.RulesDefinition$NewRule.setDebtSubCharacteristic(java.lang.String)'
	at org.sonar.squidbridge.rules.SqaleXmlLoader.processRule(SqaleXmlLoader.java:124)
	at org.sonar.squidbridge.rules.SqaleXmlLoader.processSubChar(SqaleXmlLoader.java:92)
	at org.sonar.squidbridge.rules.SqaleXmlLoader.processRoot(SqaleXmlLoader.java:78)
	at org.sonar.squidbridge.rules.SqaleXmlLoader.loadXmlResource(SqaleXmlLoader.java:65)
	at org.sonar.squidbridge.rules.SqaleXmlLoader.load(SqaleXmlLoader.java:52)
	at fr.insideapp.sonarqube.dart.lang.issues.dartanalyzer.DartAnalyzerRulesDefinition.define(DartAnalyzerRulesDefinition.java:71)
	at org.sonar.server.rule.RuleDefinitionsLoader.load(RuleDefinitionsLoader.java:56)
	at org.sonar.server.rule.RegisterRules.start(RegisterRules.java:125)
	at org.sonar.core.platform.StartableBeanPostProcessor.postProcessBeforeInitialization(StartableBeanPostProcessor.java:33)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:440)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1796)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:620)
	... 19 common frames omitted
2023.10.26 11:35:09 INFO  web[][o.s.p.ProcessEntryPoint] Hard stopping process
2023.10.26 11:35:09 INFO  web[][o.s.s.n.NotificationDaemon] Notification service stopped
2023.10.26 11:35:09 INFO  web[][c.z.h.HikariDataSource] HikariPool-1 - Shutdown initiated...
2023.10.26 11:35:09 INFO  web[][c.z.h.HikariDataSource] HikariPool-1 - Shutdown completed.
2023.10.26 11:35:09 INFO  web[][o.s.s.p.d.EmbeddedDatabase] Embedded database stopped
```

**Comment by eblackssc** [comment]
As an update, I have moved to SonarQube 10.2.1 and still have the same issue and same error.

**Comment by zippy1978** [comment]
Hi @eblackssc,
I tested it on 10.3 (10.3.0.82913) and 9.9 (9.9.1.69595) and I can't reproduce.
From the issue that you have (missing method setDebtSubCharacteristic in Sonar api), it seems you have an older version of the plugin (this method is not used anymore in the source code).

Could you check that you test with the version 0.5.0 of the plugin ?

**Comment by eblackssc** [comment]
@zippy1978 Thank you! I don't know how I missed that or how that happened. But 0.5.0 works. I really appreciate it.

**Comment by zippy1978** [comment]
You are welcome !
I close the issue for now.
