### ISSUE TITLE
sonarqube 10.7 error in Developer, Enterprise or Data Center

### ISSUE THREAD

**Issue by readonlyuser1** [insideapp-oss/sonar-flutter#238]
https://community.sonarsource.com/t/sonarqube-10-7-released/127319

SonarQube in 10.7 started analyzing Dart code in [Developer Edition](https://www.sonarsource.com/plans-and-pricing/developer/) | [Enterprise Edition](https://www.sonarsource.com/plans-and-pricing/enterprise/) | [Data Center Edition](https://www.sonarsource.com/plans-and-pricing/data-center/)

I updated sonarqube to version 10.7 and:
```
Process exited with exit value [ElasticSearch]: 143
```
**tail -f /opt/sonarqube/logs/web.log**
```2024.10.04 57 INFO  web[][o.s.p.ProcessEntryPoint] Starting Web Server
2024.10.04 58 INFO  web[][o.s.s.a.TomcatHttpConnectorFactory] Starting Tomcat
2024.10.04 59 INFO  web[][o.s.s.p.LogServerVersion] SonarQube Server / 10.7.0.96327 / 923a7aad28f71dce1686768b3ad7c4b1bb962f8d
2024.10.04 59 INFO  web[][c.z.h.HikariDataSource] HikariPool-1 - Starting...
2024.10.04 59 INFO  web[][c.z.h.p.HikariPool] HikariPool-1 - Added connection org.postgresql.jdbc.PgConnection@6df3e34c
2024.10.04 59 INFO  web[][c.z.h.HikariDataSource] HikariPool-1 - Start completed.
2024.10.04 00 INFO  web[][o.s.s.u.SystemPasscodeImpl] System authentication by passcode is disabled
2024.10.04 00 INFO  web[][o.s.c.e.CoreExtensionsLoader] Loaded core extensions: datacenter-edition, ce-workers, developer-scanner, developer-server, sca, governance, fix-suggestions, ai-code-assurance, github-provisioning, gitlab-provisioning, ha, license, securityreport, monitoring, scim, gitlab-vulnerability-report
2024.10.04 01 INFO  web[][o.s.s.p.ServerPluginManager] Deploy ABAP Code Quality and Security / 3.14.0.5470 / ed8f535cc76a0a2be68bcfd2de29eff22412e83f
2024.10.04 01 INFO  web[][o.s.s.p.ServerPluginManager] Deploy Apex Code Quality and Security / 1.17.1.109 / b7c8d0d3ec7d22f86169f3a7c5534e0001478542
2024.10.04 01 INFO  web[][o.s.s.p.ServerPluginManager] Deploy C# Code Quality and Security / 9.32.0.97167 / cc0ba76c09677fe094621d35ab0c408bd1215aaa
2024.10.04 01 INFO  web[][o.s.s.p.ServerPluginManager] Deploy CFamily Code Quality and Security / 6.59.0.75237 / 7d10d2f83d5882634f3936cfea7f0131b865018e
2024.10.04 01 INFO  web[][o.s.s.p.ServerPluginManager] Deploy CFamily dependencies provider / 6.59.0.75237 / 7d10d2f83d5882634f3936cfea7f0131b865018e
2024.10.04 01 INFO  web[][o.s.s.p.ServerPluginManager] Deploy COBOL Code Quality / 5.7.0.8061 / ac621f9052b9ca0bd0f2c240c366afcd4f5194ff
2024.10.04 01 INFO  web[][o.s.s.p.ServerPluginManager] Deploy Checkstyle / 10.17.0 /
2024.10.04 01 INFO  web[][o.s.s.p.ServerPluginManager] Deploy Clean as You Code / 2.4.0.2018 / c2f7910f6ecac6faa73001eeac4bd79a2db98cd3
2024.10.04 01 INFO  web[][o.s.s.p.ServerPluginManager] Deploy Dataflow Bug Detection / 1.31.0.11180 / 0
2024.10.04 01 INFO  web[][o.s.s.p.ServerPluginManager] Deploy Dataflow Bug Detection Rules for Java / 1.31.0.11180 / 0
2024.10.04 01 INFO  web[][o.s.s.p.ServerPluginManager] Deploy Dataflow Bug Detection Rules for Python / 1.31.0.11180 / 0
2024.10.04 01 INFO  web[][o.s.s.p.ServerPluginManager] Deploy Delphi / 1.9.0 / null
2024.10.04 01 INFO  web[][o.s.s.p.ServerPluginManager] Deploy Dependency-Check / 5.0.0 / 80796c2480568783b68643c112c16fa3e0bbc3fc
2024.10.04 01 INFO  web[][o.s.s.p.ServerPluginManager] Deploy Findbugs / 4.2.10 /
2024.10.04 01 INFO  web[][o.s.s.p.ServerPluginManager] Deploy Flex Code Quality and Security / 2.12.0.4568 / e8b2821a05db57b79b8ae85e3db1571f5b744273
2024.10.04 01 INFO  web[][o.s.s.p.ServerPluginManager] Deploy Flutter / 0.5.2 / null
2024.10.04 01 INFO  web[][o.s.s.p.ServerPluginManager] Deploy Go Code Quality and Security / 1.17.1.145 / 9361aec32c690949f436d992e2cdab0c8474faa1
2024.10.04 01 INFO  web[][o.s.s.p.ServerPluginManager] Deploy HTML Code Quality and Security / 3.16.0.5274 / 423029a90fcbbd65b86d3b4e9c3e4bc686449a75
2024.10.04 01 INFO  web[][o.s.s.p.ServerPluginManager] Deploy IaC Code Quality and Security / 1.36.0.12431 / null
2024.10.04 01 INFO  web[][o.s.s.p.ServerPluginManager] Deploy JCL Code Quality / 1.3.0.1243 / 0
2024.10.04 01 INFO  web[][o.s.s.p.ServerPluginManager] Deploy JaCoCo / 1.3.0.1538 / 74a7798c7cea687c72ed9df40c93eb7ea2a58c49
2024.10.04 01 INFO  web[][o.s.s.p.ServerPluginManager] Deploy Java Advanced Code Quality Analyzer / 8.2.0.36672 / 62f908723e8d3d071378116ab09b075933d8bf63
2024.10.04 01 INFO  web[][o.s.s.p.ServerPluginManager] Deploy Java Code Quality and Security / 8.2.0.36672 / 62f908723e8d3d071378116ab09b075933d8bf63
2024.10.04 01 INFO  web[][o.s.s.p.ServerPluginManager] Deploy JavaScript/TypeScript/CSS Code Quality and Security / 10.16.0.27621 / 49be78091aeac33f18bf0d8a0a88ec58b437cba8
2024.10.04 01 INFO  web[][o.s.s.p.ServerPluginManager] Deploy Kotlin Code Quality and Security / 2.20.0.4382 / eb22cc4ed915de84e358135dd3f2ea2080de1441
2024.10.04 01 INFO  web[][o.s.s.p.ServerPluginManager] Deploy PHP Code Quality and Security / 3.38.0.12239 / 279677ad6708471575fb0b54b43d16084903bdf2
2024.10.04 01 INFO  web[][o.s.s.p.ServerPluginManager] Deploy PL/I Code Quality and Security / 1.15.0.4810 / 9a38207e30a026fef7a06a3826e3a90da81a58bf
2024.10.04 01 INFO  web[][o.s.s.p.ServerPluginManager] Deploy PL/SQL Code Quality and Security / 3.14.0.6845 / f0bb146ce7daaa7f6c0487de2a3ae38a432e7704
2024.10.04 01 INFO  web[][o.s.s.p.ServerPluginManager] Deploy PVS-Studio Plugin / 7.29.79138.2160 / null
2024.10.04 01 INFO  web[][o.s.s.p.ServerPluginManager] Deploy Python Code Quality and Security / 4.22.0.16914 / 9e24dce6ea3e7b10fc2cf3942dc0a921049c5355
2024.10.04 01 INFO  web[][o.s.s.p.ServerPluginManager] Deploy RPG Code Quality / 3.9.0.5001 / 8bb7690b021b87369942b32b36074833f1ed8654
2024.10.04 01 INFO  web[][o.s.s.p.ServerPluginManager] Deploy Ruby Code Quality and Security / 1.17.1.134 / d58bcbdc7aae6e6d287f2b41972c5a1bba078a83
2024.10.04 01 INFO  web[][o.s.s.p.ServerPluginManager] Deploy Scala Code Quality and Security / 1.17.1.166 / 6153bdc7bf9bce07f2ac71be3aee633b9fd0bcb9
2024.10.04 01 INFO  web[][o.s.s.p.ServerPluginManager] Deploy Swift Code Quality and Security / 4.12.0.7262 / f947de544e18adb09cf1d5397bf3e5956d49fde9
2024.10.04 01 INFO  web[][o.s.s.p.ServerPluginManager] Deploy T-SQL Code Quality and Security / 1.13.0.7207 / 0a2e8cc6c03c6d89732c262028aa2547c9918efd
2024.10.04 01 INFO  web[][o.s.s.p.ServerPluginManager] Deploy Text Code Quality and Security / 2.16.0.4008 / null
2024.10.04 01 INFO  web[][o.s.s.p.ServerPluginManager] Deploy Text Code Quality and Security / 2.16.0.4008 / null
2024.10.04 01 INFO  web[][o.s.s.p.ServerPluginManager] Deploy VB.NET Code Quality and Security / 9.32.0.97167 / cc0ba76c09677fe094621d35ab0c408bd1215aaa
2024.10.04 01 INFO  web[][o.s.s.p.ServerPluginManager] Deploy VB6 Code Quality and Security / 2.13.0.5130 / 7cc85a789d9bf302eea181fe67d4a2c9c71ad005
2024.10.04 01 INFO  web[][o.s.s.p.ServerPluginManager] Deploy Vulnerability Analysis / 10.7.0.32997 / 9384a8136ba7e43eaf5d41750ad72c97ec8dca3e
2024.10.04 01 INFO  web[][o.s.s.p.ServerPluginManager] Deploy Vulnerability Rules for C# / 10.7.0.32997 / 9384a8136ba7e43eaf5d41750ad72c97ec8dca3e
2024.10.04 01 INFO  web[][o.s.s.p.ServerPluginManager] Deploy Vulnerability Rules for JS / 10.7.0.32997 / 9384a8136ba7e43eaf5d41750ad72c97ec8dca3e
2024.10.04 01 INFO  web[][o.s.s.p.ServerPluginManager] Deploy Vulnerability Rules for Java / 10.7.0.32997 / 9384a8136ba7e43eaf5d41750ad72c97ec8dca3e
2024.10.04 01 INFO  web[][o.s.s.p.ServerPluginManager] Deploy Vulnerability Rules for PHP / 10.7.0.32997 / 9384a8136ba7e43eaf5d41750ad72c97ec8dca3e
2024.10.04 01 INFO  web[][o.s.s.p.ServerPluginManager] Deploy Vulnerability Rules for Python / 10.7.0.32997 / 9384a8136ba7e43eaf5d41750ad72c97ec8dca3e
2024.10.04 01 INFO  web[][o.s.s.p.ServerPluginManager] Deploy XML Code Quality and Security / 2.10.0.4108 / 34b16ba369117f6befc0b1e0866a069a80f6db2e
2024.10.04 01 INFO  web[][o.s.s.p.ServerPluginManager] Deploy Z PL/SQL Analyzer / 3.5.1 / null
2024.10.04 01 INFO  web[][o.s.s.p.ServerPluginManager] Deploy dart / 0.2.0.1567 / null
2024.10.04 05 INFO  web[][o.s.s.p.d.m.c.PostgresCharsetHandler] Verify that database charset supports UTF8
2024.10.04 05 INFO  web[][o.s.s.e.EsClientProvider] Connected to Elasticsearch
2024.10.04 06 INFO  web[][o.s.s.p.w.MasterServletFilter] Initializing servlet filter org.sonar.server.platform.web.WebServiceFilter@ac4e690 [pattern=UrlPattern{inclusions=[/api/system/migrate_db.*, ...], exclusions=[/api/components/update_key, ...]}]
2024.10.04 06 INFO  web[][o.s.s.p.DetectPluginChange] Detect plugin changes
2024.10.04 06 ERROR web[][o.s.s.p.Platform] Background initialization failed. Stopping SonarQube
java.lang.IllegalStateException: Fail to load plugin dart [dart]
        at org.sonar.server.plugins.ServerExtensionInstaller.installExtensions(ServerExtensionInstaller.java:81)
        at org.sonar.server.platform.platformlevel.PlatformLevel4.start(PlatformLevel4.java:731)
        at org.sonar.server.platform.PlatformImpl.start(PlatformImpl.java:214)
        at org.sonar.server.platform.PlatformImpl.startLevel34Containers(PlatformImpl.java:194)
        at org.sonar.server.platform.PlatformImpl$AutoStarterRunnable.runIfNotAborted(PlatformImpl.java:362)
        at org.sonar.server.platform.PlatformImpl$1.doRun(PlatformImpl.java:113)
        at org.sonar.server.platform.PlatformImpl$AutoStarterRunnable.run(PlatformImpl.java:346)
        at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: org.springframework.beans.factory.support.BeanDefinitionOverrideException: Invalid bean definition with name 'jdk.internal.loader.ClassLoaders$AppClassLoader@5ffd2b27-org.sonar.api.config.PropertyDefinition-sonar.dart.file.suffixes' defined in null: Cannot register bean definition [Generic bean: class [org.sonar.api.config.PropertyDefinition]; scope=singleton; abstract=false; lazyInit=null; autowireMode=0; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=null; factoryMethodName=null; initMethodName=null; destroyMethodName=null] for bean 'jdk.internal.loader.ClassLoaders$AppClassLoader@5ffd2b27-org.sonar.api.config.PropertyDefinition-sonar.dart.file.suffixes': There is already [Generic bean: class [org.sonar.api.config.PropertyDefinition]; scope=singleton; abstract=false; lazyInit=null; autowireMode=0; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=null; factoryMethodName=null; initMethodName=null; destroyMethodName=null] bound.
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.registerBeanDefinition(DefaultListableBeanFactory.java:1006)
        at org.springframework.context.support.GenericApplicationContext.registerBeanDefinition(GenericApplicationContext.java:342)
        at org.springframework.beans.factory.support.BeanDefinitionReaderUtils.registerBeanDefinition(BeanDefinitionReaderUtils.java:164)
        at org.springframework.context.annotation.AnnotatedBeanDefinitionReader.doRegisterBean(AnnotatedBeanDefinitionReader.java:285)
        at org.springframework.context.annotation.AnnotatedBeanDefinitionReader.registerBean(AnnotatedBeanDefinitionReader.java:233)
        at org.springframework.context.annotation.AnnotationConfigApplicationContext.registerBean(AnnotationConfigApplicationContext.java:198)
        at org.sonar.core.platform.SpringComponentContainer.registerInstance(SpringComponentContainer.java:148)
        at org.sonar.core.platform.SpringComponentContainer.addExtension(SpringComponentContainer.java:164)
        at org.sonar.core.platform.SpringComponentContainer.addExtension(SpringComponentContainer.java:261)
        at org.sonar.core.platform.SpringComponentContainer.addExtension(SpringComponentContainer.java:41)
        at org.sonar.server.plugins.ServerExtensionInstaller.installExtension(ServerExtensionInstaller.java:89)
        at org.sonar.server.plugins.ServerExtensionInstaller.installExtensions(ServerExtensionInstaller.java:73)
        ... 7 common frames omitted
2024.10.04 06 INFO  web[][o.h.v.i.util.Version] HV000001: Hibernate Validator null
2024.10.04 07 INFO  web[][o.s.p.ProcessEntryPoint] Hard stopping process
2024.10.04 07 INFO  web[][c.z.h.HikariDataSource] HikariPool-1 - Shutdown initiated...
2024.10.04 07 INFO  web[][c.z.h.HikariDataSource] HikariPool-1 - Shutdown completed.
 ```
after
  ```
rm /sonarqube/extensions/plugins/sonar-flutter-plugin-0.5.2.jar
 ```
SonarQube starts normally

**Comment by sarn0ld** [comment]
When Dart ist supported out of the box after updating to SonarQube 10.7, do we still need this plugin? 🤔 

Can anybody provide migration instructions?

**Comment by zippy1978** [comment]
Hi,

Yes that is the exact problem: "dart" language is now supported out of the box in developer, enterprise and data center editions.

So, if you have a developer, enterprise or data center edition of SonarQube: you can uninstall the plugin (otherwise SonarQube wont't start because of "dart" language detected twice - as shown above).

If you have a community edition: you can keep using this plugin.
