### ISSUE TITLE
Plugin fails if dartanalyzer returns with non-zero error code

### ISSUE THREAD

**Issue by jrehwaldt** [insideapp-oss/sonar-flutter#41]
When `dartanalyzer` returns non-zero error codes `sonar-scanner` should continue to run successfully and report any found issues.

Currently, `dartanalyzer` handles certain types of issues by returning with codes 1-3 instead of 0. For example, when `dartanalyzer` finds errors, it will return with status code 3. This plugin will then fail with the following error:

```
INFO: Sensor Dart sensor [flutter] (done) | time=3606ms
INFO: Sensor dartanalyzer sensor [flutter]
INFO: Backup of original analysis_options.yaml file to analysis_options.yaml.sonar
INFO: ------------------------------------------------------------------------
INFO: EXECUTION FAILURE
INFO: ------------------------------------------------------------------------
INFO: Total time: 10:00.681s
INFO: Final Memory: 103M/344M
INFO: ------------------------------------------------------------------------
ERROR: Error during SonarQube Scanner execution
org.buildobjects.process.ExternalProcessFailureException: External process 'dartanalyzer [libs here]' returned 3 after 20059ms
	at org.buildobjects.process.Proc.<init>(Proc.java:124)
	at org.buildobjects.process.ProcBuilder.run(ProcBuilder.java:205)
	at fr.insideapp.sonarqube.dart.lang.issues.dartanalyzer.DartAnalyzerSensor.execute(DartAnalyzerSensor.java:94)
```

Instead, it should properly parse the list of issues and report them, ignoring the error code.

```
dart --version
Dart SDK version: 2.11.0-213.1.beta (beta) (Wed Oct 14 10:49:52 2020 +0200) on "macos_x64
```

**Comment by jrehwaldt** [comment]
Sorry for the confusion, we were using an outdated version.
