### ISSUE TITLE
timeout after 60000ms

### ISSUE THREAD

**Issue by zaralockheart** [insideapp-oss/sonar-flutter#9]
```
org.buildobjects.process.TimeoutException: Process 'dartanalyzer lib/ui/feature/login.dart lib/ui/ui_util.dart 
...bunch of file directories....
lib/ui/feature/profile.dart lib/ui/feature/user.dart' timed out after 600000ms.
	at org.buildobjects.process.Proc.killCleanUpAndThrowTimeoutException(Proc.java:169)
	at org.buildobjects.process.Proc.<init>(Proc.java:101)
	at org.buildobjects.process.ProcBuilder.run(ProcBuilder.java:205)
	at fr.insideapp.sonarqube.dart.lang.issues.dartanalyzer.DartAnalyzerSensor.execute(DartAnalyzerSensor.java:94)
	at org.sonar.scanner.sensor.AbstractSensorWrapper.analyse(AbstractSensorWrapper.java:48)
	at org.sonar.scanner.sensor.ModuleSensorsExecutor.execute(ModuleSensorsExecutor.java:85)
	at org.sonar.scanner.sensor.ModuleSensorsExecutor.lambda$execute$1(ModuleSensorsExecutor.java:59)
	at org.sonar.scanner.sensor.ModuleSensorsExecutor.withModuleStrategy(ModuleSensorsExecutor.java:77)
	at org.sonar.scanner.sensor.ModuleSensorsExecutor.execute(ModuleSensorsExecutor.java:59)
	at org.sonar.scanner.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:82)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:136)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:122)
	at org.sonar.scanner.scan.ProjectScanContainer.scan(ProjectScanContainer.java:386)
	at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:382)
	at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:351)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:136)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:122)
	at org.sonar.scanner.bootstrap.GlobalContainer.doAfterStart(GlobalContainer.java:141)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:136)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:122)
	at org.sonar.batch.bootstrapper.Batch.doExecute(Batch.java:72)
	at org.sonar.batch.bootstrapper.Batch.execute(Batch.java:66)
	at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:46)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
	at com.sun.proxy.$Proxy0.execute(Unknown Source)
	at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:189)
	at org.sonarsource.scanner.api.EmbeddedScanner.execute(EmbeddedScanner.java:138)
	at org.sonarsource.scanner.cli.Main.execute(Main.java:112)
	at org.sonarsource.scanner.cli.Main.execute(Main.java:75)
	at org.sonarsource.scanner.cli.Main.main(Main.java:61)
```

We are trying to implement this in our existing project, apparently we were hit by this issue which cause the pipeline fails.

**Comment by zaralockheart** [comment]
I little bit of digging, I see that the timeout is set too `private static final int ANALYZER_TIMEOUT = 10 * 60 * 1000;` and it's used [here](https://github.com/insideapp-oss/sonar-flutter/blob/master/dart-lang/src/main/java/fr/insideapp/sonarqube/dart/lang/issues/dartanalyzer/DartAnalyzerSensor.java#L91-L95). Can I know what cause the `ProcBuilder` take long time?

**Comment by zaralockheart** [comment]
```
java version "1.8.0_241"
Java(TM) SE Runtime Environment (build 1.8.0_241-b07)
Java HotSpot(TM) 64-Bit Server VM (build 25.241-b07, mixed mode)

SonarQube : Community EditionVersion 8.1 (build 31237)
```

**Comment by zippy1978** [comment]
Hi @zaralockheart ,

Ok, there is a timeout on the dartanalyzer command.
Could you try to run dartanalyzer from command line to see how it behaves ?

Gilles

**Comment by zaralockheart** [comment]
Sorry :( Due to restricted movement order in our country I don't have access to this repo (internal server) I'll update after we are back to business, it could take a few weeks. At this point, Dartanalyzer is running fine on my machine.

**Comment by zaralockheart** [comment]
I tried this out with my local machine: Here's the log

<details>

```
INFO: Scanner configuration file: /usr/local/Cellar/sonar-scanner/4.2.0.1873/libexec/conf/sonar-scanner.properties
INFO: Project root configuration file: /Users/muhammadyusufrosman/workspace/smile-flutter-app/sonar-project.properties
INFO: SonarQube Scanner 4.2.0.1873
INFO: Java 13.0.2 Oracle Corporation (64-bit)
INFO: Mac OS X 10.15.3 x86_64
INFO: User cache: /Users/muhammadyusufrosman/.sonar/cache
INFO: SonarQube server 8.2.0
INFO: Default locale: "en_MY", source code encoding: "UTF-8"
INFO: Load global settings
INFO: Load global settings (done) | time=117ms
INFO: Server id: BF41A1F2-AXFdENyhfH2BHRcJtshw
INFO: User cache: /Users/muhammadyusufrosman/.sonar/cache
INFO: Load/download plugins
INFO: Load plugins index
INFO: Load plugins index (done) | time=45ms
INFO: Load/download plugins (done) | time=831ms
INFO: Process project properties
INFO: Process project properties (done) | time=7ms
INFO: Execute project builders
INFO: Execute project builders (done) | time=4ms
INFO: Project key: smile-flutter
INFO: Base dir: /Users/muhammadyusufrosman/workspace/smile-flutter-app
INFO: Working dir: /Users/muhammadyusufrosman/workspace/smile-flutter-app/.scannerwork
INFO: Load project settings for component key: 'smile-flutter'
INFO: Load project settings for component key: 'smile-flutter' (done) | time=113ms
INFO: Load quality profiles
INFO: Load quality profiles (done) | time=215ms
INFO: Load active rules
INFO: Load active rules (done) | time=2793ms
INFO: Indexing files...
INFO: Project configuration:
INFO: 740 files indexed
INFO: 0 files ignored because of scm ignore settings
INFO: Quality profile for dart: dartanalyzer
INFO: ------------- Run sensors on module smile-flutter
INFO: Load metrics repository
INFO: Load metrics repository (done) | time=24ms
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by net.sf.cglib.core.ReflectUtils$1 (file:/Users/muhammadyusufrosman/.sonar/cache/54f6535c111cefad0fb6a09ba3e61922/sonar-javascript-plugin.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of net.sf.cglib.core.ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
INFO: Sensor SonarCSS Rules [cssfamily]
INFO: No CSS, PHP, HTML or VueJS files are found in the project. CSS analysis is skipped.
INFO: Sensor SonarCSS Rules [cssfamily] (done) | time=2ms
INFO: Sensor JaCoCo XML Report Importer [jacoco]
INFO: Sensor JaCoCo XML Report Importer [jacoco] (done) | time=7ms
INFO: Sensor Dart sensor [flutter]
INFO: Load project repositories
INFO: Load project repositories
INFO: Load project repositories
INFO: Load project repositories
INFO: Load project repositories
INFO: Load project repositories (done) | time=78ms
INFO: Load project repositories (done) | time=76ms
INFO: Load project repositories (done) | time=79ms
INFO: Load project repositories (done) | time=75ms
INFO: Load project repositories (done) | time=57ms
// Loads of duplication report as this from tests directory
Duplication reported for 'test/ui/mcs/ui/reader_test.dart' will be ignored because it's a test file.
INFO: Sensor Dart sensor [flutter] (done) | time=8069ms
INFO: Sensor dartanalyzer sensor [flutter]
INFO: Backup of original analysis_options.yaml file to analysis_options.yaml.sonar
INFO: Restored original analysis_options.yaml file
INFO: Sensor dartanalyzer sensor [flutter] (done) | time=481223ms
INFO: Sensor Flutter unit tests [flutter]
INFO: ------------------------------------------------------------------------
INFO: EXECUTION FAILURE
INFO: ------------------------------------------------------------------------
INFO: Total time: 8:17.034s
INFO: Final Memory: 331M/1127M
INFO: ------------------------------------------------------------------------
ERROR: Error during SonarQube Scanner execution
java.lang.NullPointerException
        at fr.insideapp.sonarqube.flutter.tests.FlutterTestReportParser.parse(FlutterTestReportParser.java:58)
        at fr.insideapp.sonarqube.flutter.tests.FlutterTestReportParser.parse(FlutterTestReportParser.java:42)
        at fr.insideapp.sonarqube.flutter.tests.FlutterTestSensor.execute(FlutterTestSensor.java:57)
        at org.sonar.scanner.sensor.AbstractSensorWrapper.analyse(AbstractSensorWrapper.java:48)
        at org.sonar.scanner.sensor.ModuleSensorsExecutor.execute(ModuleSensorsExecutor.java:85)
        at org.sonar.scanner.sensor.ModuleSensorsExecutor.lambda$execute$1(ModuleSensorsExecutor.java:59)
        at org.sonar.scanner.sensor.ModuleSensorsExecutor.withModuleStrategy(ModuleSensorsExecutor.java:77)
        at org.sonar.scanner.sensor.ModuleSensorsExecutor.execute(ModuleSensorsExecutor.java:59)
        at org.sonar.scanner.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:82)
        at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:136)
        at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:122)
        at org.sonar.scanner.scan.ProjectScanContainer.scan(ProjectScanContainer.java:386)
        at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:382)
        at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:351)
        at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:136)
        at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:122)
        at org.sonar.scanner.bootstrap.GlobalContainer.doAfterStart(GlobalContainer.java:141)
        at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:136)
        at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:122)
        at org.sonar.batch.bootstrapper.Batch.doExecute(Batch.java:72)
        at org.sonar.batch.bootstrapper.Batch.execute(Batch.java:66)
        at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:46)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:567)
        at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
        at com.sun.proxy.$Proxy0.execute(Unknown Source)
        at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:189)
        at org.sonarsource.scanner.api.EmbeddedScanner.execute(EmbeddedScanner.java:138)
        at org.sonarsource.scanner.cli.Main.execute(Main.java:112)
        at org.sonarsource.scanner.cli.Main.execute(Main.java:75)
        at org.sonarsource.scanner.cli.Main.main(Main.java:61)
ERROR: 
ERROR: Re-run SonarQube Scanner using the -X switch to enable full debug logging
```

</details>

**Comment by zaralockheart** [comment]
running `dartanalyzer --options analysis_options.yaml . --format -h` showing `7298 lints and 47 hints found.` in 3 minutes.

**Comment by zaralockheart** [comment]
The issues that I faced on my machine seems like different from the issue that I open. Should I create another issue or here is fine?

**Comment by zippy1978** [comment]
Hi,
I've juste released version 0.3.0.
In this version, dartanalyzer is called on different "pages" to avoid timeout on large projects / slower machines.
Could you tell me if you still have the problem with this version ?

**Comment by gabidusa** [comment]
Hi Gilles,

I updated to v 0.3.0.
Unfortunately I had to revert to 0.2.1 as the analysis was really strange: I had a lot of errors and smells that were reported multiple times and they were not even real.
Just wanted to share this info with you.

I am sorry as I don't have the logs for the problems.

Regards,

**Comment by zippy1978** [comment]
Hi @gabidusa,

Thank you for your feedback.
Is your project large ? (how many source files ?).
It is probably related to the paginated mode (dartanalyzer launched multiple times).
It would be interesting to get he output log (sonar-scanner -X)

**Comment by gabidusa** [comment]
The project is quite small (10k lines of code).

**Comment by zippy1978** [comment]
@gabidusa,
I did a fix to prevent same issues being reported multiple times.
Could you try the version provided with this comment ?

[sonar-flutter-plugin-0.3-SNAPSHOT.jar.zip](https://github.com/insideapp-oss/sonar-flutter/files/5058188/sonar-flutter-plugin-0.3-SNAPSHOT.jar.zip)

**Comment by zippy1978** [comment]
@gabidusa,
I did some more testing on large projects, with many source files and it seems to be ok with release 0.3.1.

**Comment by gabidusa** [comment]
ok.

I will do an update.
I don’t know when I will do it, but I will let you know if all is fine or not.

Thanks!

**Comment by sharkyak** [comment]
Have the same problem with dartanalizier and 600 sec limit.
Sometimes it works. Sometimes not. Depends of cpu usage at vm with scanner.
Project ~80k lines.

Better to have an ability to increase this time limit.

![Снимок экрана 2020-11-17 в 12 49 20](https://user-images.githubusercontent.com/15677756/99367475-7456fb00-28d3-11eb-9aba-51f3ada21eb2.png)

![Снимок экрана 2020-11-17 в 12 49 34](https://user-images.githubusercontent.com/15677756/99367470-70c37400-28d3-11eb-9183-db7edc84c3ae.png)

**Comment by zaralockheart** [comment]
Sry, been a while. 0.3.1 works. Let me know if I should close this issue as others still have this issue. Thanks!

**Comment by salih-g** [comment]
Any update we are getting it now
